@extends('layouts.public')
@section('title','NACO | Skills. Discipline. Self-Reliance.')
@section('meta_description','NACO empowers Nigerian youths through practical skills, discipline, emergency response and community development.')
@section('content')
<section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Empowering Nigerian youths</span><h1>Skills that build <span>self-reliance.</span></h1><p class="lead">NACO develops capable, disciplined and resourceful young people through practical manpower skills, moral development, emergency response training and community service.</p><div class="actions"><a class="btn btn-primary" href="{{ route('programs') }}">Explore programs →</a><a class="btn btn-outline" href="{{ route('about') }}">Discover NACO</a></div></div><div class="hero-panel"><div class="hero-orbit"></div><span class="hero-label">NACO</span><strong>Skills<br>Discipline<br>Self-Reliance</strong><p>A stronger generation starts with practical preparation and purposeful service.</p></div></div></section>
<section class="section stats-section"><div class="container stats"><div class="stat"><strong>03</strong><span>Core empowerment pillars</span></div><div class="stat"><strong>06+</strong><span>Practical training pathways</span></div><div class="stat"><strong>24/7</strong><span>Emergency readiness mindset</span></div><div class="stat"><strong>01</strong><span>Mission: self-reliant youth</span></div></div></section>
<section class="section"><div class="container"><div class="section-head"><span class="section-kicker">What we do</span><h2>Practical preparation for real life.</h2><p>Our programs combine vocational capability, character development and lifesaving competence so participants can create value wherever they live.</p></div><div class="cards"><article class="card"><div class="icon">01</div><h3>Vocational Handcraft</h3><p>Hands-on pathways including tailoring, carpentry, welding, electronics and other practical trades.</p></article><article class="card"><div class="icon">02</div><h3>Emergency Response</h3><p>First aid, CPR, basic life support, rescue awareness and disaster preparedness.</p></article><article class="card"><div class="icon">03</div><h3>Character Development</h3><p>Discipline, teamwork, leadership, integrity and civic responsibility.</p></article></div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><span class="section-kicker">Leadership structure</span><h2>From national direction to the ward.</h2><p>NACO connects leadership and responsibility across national, state, LGA and ward levels.</p></div><div class="leadership-preview"><div><strong>National</strong><span>Overall direction</span></div><i>↓</i><div><strong>State</strong><span>State coordination</span></div><i>↓</i><div><strong>Chairman Self-Reliance</strong><span>LGA coordination</span></div><i>↓</i><div><strong>HCS</strong><span>Ward leadership</span></div></div><div class="center-action"><a class="btn btn-outline" href="{{ route('leadership') }}">View leadership structure →</a></div></div></section>
<section class="section"><div class="container split"><div><span class="section-kicker">Our approach</span><h2>Training beyond the classroom.</h2><p>NACO connects practical skills with responsibility. Participants learn how to solve problems, support others, develop livelihoods and contribute to community development.</p><ul class="feature-list"><li><span>✓</span><div><strong>Hands-on learning</strong><small>Practical skills designed for economic independence.</small></div></li><li><span>✓</span><div><strong>Discipline and leadership</strong><small>Structured activities that build teamwork, respect and accountability.</small></div></li><li><span>✓</span><div><strong>Community impact</strong><small>Communal labour and self-help projects turn training into service.</small></div></li><li><span>✓</span><div><strong>Self-reliance</strong><small>Entrepreneurship and mentorship support sustainable livelihoods.</small></div></li></ul></div><div class="visual-panel"><h3>Every trained youth can become a community asset.</h3><p>NACO's vision is a skilled, disciplined and self-sufficient youth population capable of transforming communities through craftsmanship, civic responsibility and lifesaving competence.</p><div class="pill-row"><span>Craftsmanship</span><span>First Aid</span><span>Rescue</span><span>Leadership</span><span>Enterprise</span></div></div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><span class="section-kicker">Three pillars</span><h2>One organization. Three pathways to impact.</h2></div><div class="service-grid"><article><span>01 / LIFE SAVING</span><h3>Emergency Response</h3><ul><li>Medical first aid and CPR</li><li>Basic life support</li><li>Water and fire response awareness</li><li>Community first responder training</li></ul></article><article><span>02 / MANPOWER</span><h3>Vocational Skills</h3><ul><li>Tailoring and fashion</li><li>Carpentry and welding</li><li>Electronics and practical trades</li><li>Entrepreneurship mentorship</li></ul></article><article><span>03 / COMMUNITY</span><h3>Character & Development</h3><ul><li>Ceremonial drills and discipline</li><li>Communal labour</li><li>Leadership and teamwork</li><li>Youth mentorship</li></ul></article></div></div></section>
<section class="section"><div class="container team-preview"><div class="section-head"><span class="section-kicker">Meet the team</span><h2>Technology supporting the mission.</h2><p>The NACO ICT Team supports the organization's digital presence and technology initiatives.</p></div><div class="cards"><article class="card person-card"><div class="avatar">AU</div><h3>Auwal Usman</h3><p>ICT Team</p></article><article class="card person-card"><div class="avatar">BA</div><h3>Babawo Ahmad</h3><p>ICT Team</p></article><article class="card person-card"><div class="avatar">YT</div><h3>Yasin Muhammed Tukur</h3><p>ICT Team</p></article></div><div class="center-action"><a class="btn btn-outline" href="{{ route('teams') }}">Meet the full team →</a></div></div></section>
<section class="section"><div class="container cta"><div><h2>Ready to build a useful skill?</h2><p>Join a practical pathway toward self-reliance, responsibility and community impact.</p></div><a class="btn btn-primary" href="{{ route('contact') }}">Get involved →</a></div></section>
@endsection