<?php
namespace App\Http\Controllers\Portal;
use App\Http\Controllers\Controller;use App\Models\FourMonthlyReport;use App\Models\ReportPeriod;use App\Models\Ward;use App\Services\ReportWorkflowService;use Illuminate\Http\Request;use Illuminate\Support\Facades\Storage;
class FourMonthlyReportController extends Controller
{
 public function index(Request $request){$u=$request->user();$q=FourMonthlyReport::with(['ward.lga.state','period'])->latest();if($u->isCadet())$q->where('submitted_by',$u->id);return view('portal.reports.index',['reports'=>$q->paginate(20)->withQueryString()]);}
 public function create(Request $request,ReportWorkflowService $service){abort_unless($request->user()->isHcs(),403);$cadet=$request->user()->cadet;abort_unless($cadet?->ward_id,403);return view('portal.reports.create',['period'=>$service->periodFor(),'ward'=>$cadet->ward]);}
 public function store(Request $request,ReportWorkflowService $service){abort_unless($request->user()->isHcs(),403);$cadet=$request->user()->cadet;abort_unless($cadet?->ward_id,403);$data=$request->validate(['summary'=>'required|string','activities'=>'nullable|array','membership'=>'nullable|array','training'=>'nullable|array','self_reliance'=>'nullable|array','finance'=>'nullable|array']);$period=$service->periodFor();$report=FourMonthlyReport::firstOrCreate(['ward_id'=>$cadet->ward_id,'report_period_id'=>$period->id],array_merge($data,['status'=>'draft','submitted_by'=>$request->user()->id]));abort_if($report->status!=='draft',422,'This period report already exists and is not editable.');$report->update($data);return redirect()->route('portal.reports.show',$report)->with('success','Report saved as draft.');}
 public function show(Request $request,FourMonthlyReport $report){$this->authorizeReport($request,$report);return view('portal.reports.show',['report'=>$report->load(['ward.lga.state','period','reviews.reviewer','attachments'])]);}
 public function submit(Request $request,FourMonthlyReport $report,ReportWorkflowService $service){abort_unless($request->user()->isHcs()&&$report->submitted_by===$request->user()->id,403);$service->submit($report,$request->user());return back()->with('success','Report submitted to Chairman Self-Reliance.');}
 public function review(Request $request,FourMonthlyReport $report,ReportWorkflowService $service){$data=$request->validate(['action'=>'required|in:approve,return','comments'=>'nullable|string|max:5000']);$level=$request->user()->isAdmin()?'national':($request->user()->isStateController()?'state':($request->user()->isChairmanSelfReliance()?'lga':null));abort_unless($level,403);$service->review($report,$request->user(),$level,$data['action'],$data['comments']??null);return back()->with('success','Report review recorded.');}
 private function authorizeReport(Request $request,FourMonthlyReport $report):void{$u=$request->user();abort_unless($u->isAdmin()||($u->cadet?->ward_id===$report->ward_id),403);}
}
