<?php
namespace App\Services;
use App\Models\FourMonthlyReport;use App\Models\ReportReview;use App\Models\ReportPeriod;use App\Models\Ward;use Illuminate\Support\Facades\DB;use Illuminate\Validation\ValidationException;
class ReportWorkflowService
{
 public function periodFor(?\DateTimeInterface $date=null):ReportPeriod{$date=$date?now()->setTimestamp($date->getTimestamp()):now();$period=intdiv(((int)$date->format('n')-1),4)+1;return ReportPeriod::firstOrCreate(['year'=>(int)$date->format('Y'),'period'=>$period],['starts_on'=>sprintf('%04d-%02d-01',(int)$date->format('Y'),($period-1)*4+1),'ends_on'=>date('Y-m-t',strtotime(sprintf('%04d-%02d-01',(int)$date->format('Y'),$period*4))),'due_on'=>date('Y-m-d',strtotime(sprintf('%04d-%02d-10',(int)$date->format('Y'),$period*4+1)))]);}
 public function submit(FourMonthlyReport $report,$user):void{if($report->status!=='draft'&&$report->status!=='returned_by_lga')throw ValidationException::withMessages(['report'=>'This report cannot be submitted in its current status.']);$report->update(['status'=>'submitted_to_lga','submitted_by'=>$user->id,'submitted_at'=>now()]);}
 public function review(FourMonthlyReport $report,$user,string $level,string $action,?string $comments=null):void{DB::transaction(function()use($report,$user,$level,$action,$comments){$expected=['lga'=>['submitted_to_lga','returned_by_lga','approved_by_lga'],'state'=>['approved_by_lga','returned_by_state','approved_by_state'],'national'=>['approved_by_state','returned_by_national','finalized']];if(!isset($expected[$level])||!in_array($report->status,$expected[$level],true))throw ValidationException::withMessages(['report'=>'This report is not available for this review level.']);$map=['return'=>['lga'=>'returned_by_lga','state'=>'returned_by_state','national'=>'returned_by_national'],'approve'=>['lga'=>'approved_by_lga','state'=>'approved_by_state','national'=>'finalized']];if(!isset($map[$action][$level]))throw ValidationException::withMessages(['action'=>'Invalid report workflow action.']);$status=$map[$action][$level];$report->update(['status'=>$status,'finalized_at'=>$status==='finalized'?now():null]);ReportReview::create(['report_id'=>$report->id,'reviewer_id'=>$user->id,'level'=>$level,'action'=>$action,'comments'=>$comments,'reviewed_at'=>now()]);});}
}
